# Author: Yi-Cheng Teng
FROM intel/hpckit:2024.2.1-0-devel-ubuntu22.04 as builder
############ Set up build environment ############
## Clone spack
RUN apt-get update -y && \
    apt-get install -y curl libibverbs-dev && \ 
    apt-get install -y autoconf libtool automake
RUN mkdir -p /opt && cd /opt && git clone -b v0.22.2 https://github.com/spack/spack.git
# What we want to install and how we want to install it
# is specified in a manifest file (spack.yaml)
RUN mkdir -p /opt/spack-environment && \
set -o noclobber \
&&  (echo spack: \
&&   echo '  mirrors:'\
&&   echo '    E4S: https://cache.e4s.io/noaa'\
&&   echo '  definitions:' \
&&   echo '  - packages_builtin:' \
&&   echo '    - bacio%oneapi@2024.2.1' \
&&   echo '    - hdf5@1.14.3%oneapi@2024.2.1' \
&&   echo '    - ip%oneapi@2024.2.1' \
&&   echo '    - libyaml@0.2.5%oneapi@2024.2.1' \
&&   echo '    - nccmp@1.9.1.0%oneapi@2024.2.1' \
&&   echo '    - netcdf-c@4.9.2%oneapi@2024.2.1' \
&&   echo '    - netcdf-fortran@4.6.1%oneapi@2024.2.1' \
&&   echo '    - sp@2.3.3%oneapi@2024.2.1' \
&&   echo '    - w3emc@2.11.0' \
&&   echo '    - w3nco@2.4.1' \
&&   echo '    - zlib%oneapi@2024.2.1' \
&&   echo '    - zlib-ng@2.1.4%oneapi@2024.2.1' \
&&   echo '  packages:' \
&&   echo '    intel-oneapi-mpi:' \
&&   echo '      buildable: false' \
&&   echo '      externals:' \
&&   echo '      - spec: intel-oneapi-mpi@2021.10.0' \
&&   echo '        path: /opt/intel/oneapi/mpi/2021.10.0' \
&&   echo '    mpi:' \
&&   echo '      require: intel-oneapi-mpi' \
&&   echo '    hdf5:' \
&&   echo '      variants: +fortran+hl+szip' \
&&   echo '    netcdf-c:' \
&&   echo '      variants: +dap' \
&&   echo '    pango:' \
&&   echo '      variants: +X' \
&&   echo '    all:' \
&&   echo '      target: [x86_64]' \
&&   echo '      providers:' \
&&   echo '        zlib-api: [zlib-ng+compat, zlib]' \
&&   echo '      compiler: [oneapi]' \
&&   echo '  specs:' \
&&   echo '  - matrix:' \
&&   echo '    - [$packages_builtin]' \
&&   echo '  concretizer:' \
&&   echo '    unify: True' \
&&   echo '  config:' \
&&   echo '    install_tree: /opt/software' \
&&   echo '  view: /opt/views/view') > /opt/spack-environment/spack.yaml
# Install the software, remove unnecessary deps
RUN . /opt/spack/share/spack/setup-env.sh && cd /opt/spack-environment && spack compiler add && spack --verbose env activate . && spack --verbose install --fail-fast && spack gc -y
## Set environment variables
ENV LD_LIBRARY_PATH /opt/views/view/lib:$LD_LIBRARY_PATH
ENV LIBRARY_PATH /opt/views/view/lib:$LIBRARY_PATH
ENV PATH $PATH:/opt/views/view/bin
############ Set up build ############
# Set the working directory inside the container
WORKDIR /apps/CEFI-regional-MOM6
# Copy everything from the repository into /apps/CEFI-regional-MOM6
COPY . /apps/CEFI-regional-MOM6
# Installation
RUN cd /apps/CEFI-regional-MOM6/builds && \
    ./linux-build.bash -m docker -p linux-intel24 -t repro -f mom6sis2
############ Create the final stage of the container build ############
FROM intel/oneapi-runtime:2024.2.1-0-devel-ubuntu22.04 as final
## copy libs and executable from builder
COPY --from=builder /opt/software /opt/software
COPY --from=builder /opt/views /opt/views
# This will include the code and all of the build from the builder stage
COPY --from=builder /apps/CEFI-regional-MOM6/builds/build/docker-linux-intel24/ocean_ice/repro/MOM6SIS2 /apps/CEFI-regional-MOM6/exec/MOM6SIS2
## Set up the run time environment
ENV LD_LIBRARY_PATH /opt/views/view/lib:$LD_LIBRARY_PATH
ENV LIBRARY_PATH /opt/views/view/lib:$LIBRARY_PATH
ENV PATH /opt/views/view/bin:/apps/CEFI-regional-MOM6/exec:$PATH
ENTRYPOINT ["/bin/bash"]
