figures_dir: 'figures/'
glorys: '/work/acr/mom6/diagnostics/glorys/glorys_sfc.nc'
model_grid: '../data/geography/ocean_static.nc'

# List of variables to rename
rename_vars:
    - geolon
    - geolat
    - geolon_c
    - geolat_c

# Actually mappings for what each variable in above list should be renamed to
rename_map:
    geolon: lon
    geolat: lat
    geolon_c: lon_b
    geolat_c: lat_b

# Domain and plotting details
domain: ocean_monthly

# Lat/lon range 
lat: 
    south: 0
    north: 60

lon:
    west: 260
    east: 330

# Xlim/ylim to plot
x: 
    min: -99
    max: -35

y:
    min: 4
    max: 59

# SST_eval settings
oisst: '/work/acr/oisstv2/' 

# Colorbar for sst plots
levels_min: 2
levels_max: 31
levels_step: 2

# Colorbar difference plots
bias_min: -2
bias_max: 2.1
bias_step: 0.25
