name: 1D mom6-cobalt Test

on:
  workflow_call:
#    inputs:
#      message:
#        required: false
#        type: string

jobs:
  run-obgc_1d-ci:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/noaa-gfdl/cefi-regional-mom6/1d_mom6_cobalt:base
      options: --user=builder

    env:
      PR_NUMBER: ${{ github.event.number }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history to prevent detached HEAD issues
          ref: ${{ github.event.pull_request.head.ref || github.ref_name }}  # Handle fork and same-repo branches
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}  # Use forked repo if available
          submodules: recursive

      - name: Download mom6sis2_debug artifact
        uses: actions/download-artifact@v4
        with:
          name: mom6sis2_debug
          path: ./temp-artifact

      - name: Copy model dataset from Docker image
        working-directory: ./exps
        run: |
          ln -fs /opt/datasets ./

      - name: Run 1D toy case and check repro across restarts
        working-directory: ./exps/OM4.single_column.COBALT
        run: |
          mkdir -p ../../builds/build/docker-linux-gnu/ocean_ice/debug
          mv ../../temp-artifact/MOM6SIS2 ../../builds/build/docker-linux-gnu/ocean_ice/debug/
          chmod +x ../../builds/build/docker-linux-gnu/ocean_ice/debug/MOM6SIS2
          ls -l -h ../../builds/build/docker-linux-gnu/ocean_ice/debug
          ./driver.sh

      - name: Run mppnccombine to combine sub-region diag outputs
        working-directory: ./exps/OM4.single_column.COBALT
        run: |
          /opt/bin/mppnccombine -64 -h 16384 -m -k 100 20040102.ocean_daily_subset.nc 20040102.ocean_daily_subset.nc.00*

      - name: Check ref
        id: check_ref
        working-directory: ./exps/OM4.single_column.COBALT
        run: |
          echo "new 48hrs ocean.stats: "
          cat ./RESTART_48hrs/ocean.stats
          echo "baseline 48 hrs ocean.stats: "
          cat ./ref/ocean.stats
          diff -q ref/ocean.stats ./RESTART_48hrs/ocean.stats > /dev/null || { echo "Error: ocean.stats are different."; echo "Plz update exps/OM4.single_column.COBALT/ref/ocean.stats with the following: "; cat ./RESTART_48hrs/ocean.stats; exit 1; }

      - name: Check oxygen budget closure
        id: check_o2
        working-directory: ./exps/OM4.single_column.COBALT
        run: |
          # Select second time step
          ncks -d time,1 20040101.ocean_cobalt_budget.nc o2_col_budget.nc
          # Average over xh and yh
          ncwa -a xh,yh o2_col_budget.nc -O o2_col_budget.nc
          # Check residual for surface layer
          ncks -d zl,0 o2_col_budget.nc o2_sfc_budget.nc
          resid=$( ncap2 -s 'result = o2h_tendency -
              (o2_advection_xy + o2h_tendency_vert_remap + o2_vdiffuse_impl + o2_diffusion_xy + jo2h);
              print(result)' o2_sfc_budget.nc |  awk -F'=' '{print $2}')
          python3 check_residual.py $resid
          # Check residual for column total
          ncwa -y ttl -a zl o2_col_budget.nc o2_tot_budget.nc
          resid=$( ncap2 -s 'result = o2h_tendency -
              (o2_advection_xy + o2h_tendency_vert_remap + o2_vdiffuse_impl + o2_diffusion_xy + jo2h);
              print(result)' o2_tot_budget.nc |  awk -F'=' '{print $2}')
          python3 check_residual.py $resid

      - name: Check alkalinity budget closure
        id: check_alk
        working-directory: ./exps/OM4.single_column.COBALT
        run: |
          # Select second time step
          ncks -d time,1 20040101.ocean_cobalt_budget.nc alk_col_budget.nc
          # Average over xh and yh
          ncwa -a xh,yh alk_col_budget.nc -O alk_col_budget.nc
          # Check residual for surface layer
          ncks -d zl,0 alk_col_budget.nc alk_sfc_budget.nc
          resid=$( ncap2 -s 'result = alkh_tendency -
              (alk_advection_xy + alkh_tendency_vert_remap + alk_vdiffuse_impl + alk_diffusion_xy + jalkh);
              print(result)' alk_sfc_budget.nc |  awk -F'=' '{print $2}')
          python3 check_residual.py $resid
          # Check residual for column total
          ncwa -y ttl -a zl alk_col_budget.nc alk_tot_budget.nc
          resid=$( ncap2 -s 'result = alkh_tendency -
              (alk_advection_xy + alkh_tendency_vert_remap + alk_vdiffuse_impl + alk_diffusion_xy + jalkh);
              print(result)' alk_tot_budget.nc |  awk -F'=' '{print $2}')
          python3 check_residual.py $resid

      - name: Check nitrate budget closure
        id: check_no3
        working-directory: ./exps/OM4.single_column.COBALT
        run: |
          # Select second time step
          ncks -d time,1 20040101.ocean_cobalt_budget.nc no3_col_budget.nc
          # Average over xh and yh
          ncwa -a xh,yh no3_col_budget.nc -O no3_col_budget.nc
          # Check residual for surface layer
          ncks -d zl,0 no3_col_budget.nc no3_sfc_budget.nc
          resid=$( ncap2 -s 'result = no3h_tendency -
              (no3_advection_xy + no3h_tendency_vert_remap + no3_vdiffuse_impl + no3_diffusion_xy + jno3h);
              print(result)' no3_sfc_budget.nc |  awk -F'=' '{print $2}')
          python3 check_residual.py $resid
          # Check residual for column total
          ncwa -y ttl -a zl no3_col_budget.nc no3_tot_budget.nc
          resid=$( ncap2 -s 'result = no3h_tendency -
              (no3_advection_xy + no3h_tendency_vert_remap + no3_vdiffuse_impl + no3_diffusion_xy + jno3h);
              print(result)' no3_tot_budget.nc |  awk -F'=' '{print $2}')
          python3 check_residual.py $resid

      - name: Commit and push parameter doc updates
        if: steps.check_ref.outcome == 'success' && github.event_name == 'pull_request'
        working-directory: ./exps/OM4.single_column.COBALT
        run: |
          # Add repo to Git safe directory list to avoid "dubious ownership" error
          git config --global --add safe.directory /__w/CEFI-regional-MOM6/CEFI-regional-MOM6

          # Configure GitHub Actions bot credentials
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Ensure you are on the PR branch
          git fetch origin
          git checkout ${{ github.event.pull_request.head.ref }}
          git pull origin ${{ github.event.pull_request.head.ref }}

          # Add and commit parameter doc changes
          git add MOM_parameter_doc.* SIS_parameter_doc.* COBALT_parameter_doc.*

          if git diff --cached --quiet; then
            echo "No parameter doc changes detected."
          else
            # Commit and push
            git commit -m "Update parameter documentation files for 1D case"
            git push "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.event.pull_request.head.repo.full_name }}" HEAD:${{ github.event.pull_request.head.ref }}
          fi
