name: dumbbell CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  run-dumbbell-ci:
    runs-on: ubuntu-latest

    container:
        image: clouden90/1d_mom6_cobalt:base
        options: --user=root

    env:
      PR_NUMBER: ${{ github.event.number }}        

    steps:        
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Ensure full history to prevent detached HEAD issues
        ref: ${{ github.event.pull_request.head.ref || github.ref_name }}  # Handle fork and same-repo branches
        repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}  # Use forked repo if available
        submodules: recursive      
          
    - name: Build mom6-sis2-cobalt
      working-directory: ./builds
      run: |
        echo "build mom6-sis2-cobalt ..."
        ./linux-build.bash -m docker -p linux-gnu -t debug -f mom6sis2


    - name: Run dumbbell driver
      working-directory: ./exps/dumbbell/z_sub
      run: |
        echo "Start dumbbell test ..."
        ./driver.sh
