name: fun-tide-ci

on:
  push:
    branches: [ "tide_ci" ]

#
env:
  TEST_DIR: ${{ github.workspace }}/${{ github.run_id }}
  PR_NUMBER: ${{ github.event.number }}
  img: /gpfs/f6/ira-cefi/world-shared/container/cefi_mom6_intel_2024.2.1.sif
  MPICH_SMP_SINGLE_COPY_MODE: NONE
  APPTAINERENV_LD_LIBRARY_PATH: "${{ env.CLAY_LD_LIBRARY_PATH }}:${{ env.LD_LIBRARY_PATH }}:/opt/cray/pe/lib64:/usr/lib64/libibverbs:/opt/cray/libfabric/1.20.1/lib64:/opt/cray/pals/1.4/lib"
  APPTAINER_CONTAINLIBS: "/usr/lib64/libjansson.so.4,/usr/lib64/libjson-c.so.3,/usr/lib64/libcxi.so.1,/usr/lib64/libdrm.so.2,/lib64/libtinfo.so.6,/usr/lib64/libnl-3.so.200,/usr/lib64/librdmacm.so.1,/usr/lib64/libibverbs.so.1,/usr/lib64/libibverbs/libmlx5-rdmav34.so,/usr/lib64/libnuma.so.1,/usr/lib64/libnl-cli-3.so.200,/usr/lib64/libnl-genl-3.so.200,/usr/lib64/libnl-nf-3.so.200,/usr/lib64/libnl-route-3.so.200,/usr/lib64/libnl-idiag-3.so.200,/usr/lib64/libnl-xfrm-3.so.200"
  APPTAINER_BIND: "/usr/share/libdrm,/var/spool/slurmd,/opt/cray,/opt/intel,/etc/libibverbs.d,/usr/lib64/libibverbs,/usr/lib64/libnl3-200"
  SINGULARITY_SHELL: /bin/bash

#
jobs:
  checkout-build:
    runs-on: [self-hosted, gaea-c5] 
    timeout-minutes: 360

    steps:
    - name: Checkout CEFI-regional-MOM6
      uses: actions/checkout@v4
      with:
        path: ${{ github.run_id }}/MOM6_TIDE
        fetch-depth: 0   # Fetch full history to prevent detached HEAD issues
        ref: ${{ github.event.pull_request.head.ref || github.ref_name }}
        repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
        submodules: recursive

    - name: Build MOM6SIS2 using container
      run: |
        cd ${{ env.TEST_DIR }}/MOM6_TIDE/builds
        pwd
        echo "SIF image path: $img"
        apptainer exec -B /gpfs -B /ncrc/home2/Yi-cheng.Teng:/ncrc/home2/Yi-cheng.Teng $img bash linux-build.bash -m docker -p linux-intel -t repro -f mom6solo        

    - name: Clean-up workspace
      run: |
        echo "Cleaning up ${{ env.TEST_DIR }}"
        rm -rf ${{ env.TEST_DIR }}        
