name: get_glorys_data_ci

on:
  schedule:
    - cron: '0 12 * * *'    

jobs:
  get-glorys-data-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:        
    - uses: actions/checkout@v4        
    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: "latest"
        activate-environment: cmc
        environment-file: tools/initial/copernicusmarine-env.yml
        auto-activate-base: false
    - run: |
       conda info --envs
       cd tools/initial
       copernicusmarine --version
       bash get_glorys_data.sh -u ${{secrets.CMCID}} -p ${{secrets.CMCPASSWD}} -o "./" -x -100 -X -35 -y 0 -Y 60 -s "1993-01-01" -e "1993-01-01"
       pwd
       ls
       if [[ -f "/home/runner/work/CEFI-regional-MOM6/CEFI-regional-MOM6/tools/initial/GLORYS_REANALYSIS_1993-01-01.nc" ]]; then
          echo "File exists. Success..."
       else
         echo "FATAL: GLORYS_REANALYSIS_1993-01-01.nc does not exist. Exiting."
         exit 1
       fi
