name: get_glorys_data_ci

on:
  push:
    branches: [ "fix/copernicusmarine" ]
  pull_request:
    branches: [ "fix/copernicusmarine" ]

jobs:
  get-glorys-data-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:        
    - uses: actions/checkout@v4        
    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: "latest"
        activate-environment: cmc
        environment-file: tools/initial/copernicusmarine-env.yml
        auto-activate-base: false
    - run: |
       conda info --envs
       #conda activate cmc
       #conda info --envs
       #cd tools/initial
       #copernicusmarine --help
        
#    - name: Test get_glorts_data.sh
#      run: |     
#        cd tools/initial
#        copernicusmarine --help
#        #./get_glorys_data.sh -u ${{secrets.CMCID}} -p ${{secrets.CMCPASSWD}} -o "./" -x -100 -X -35 -y 0 -Y 60 -s "1993-01-01" -e "1993-01-01"
#        #[ ! -f "GLORYS_REANALYSIS_1993-01-01.nc" ] && echo "FATAL: GLORYS_REANALYSIS_1993-01-01.nc does not exist. Exiting." && exit 1
