on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight
    - cron: '25 14 * * *' # Run at 10:25am EDT (14:25 UTC)


jobs:
  stable_nightly_update:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Merge develop into main
        if: github.ref == 'refs/heads/feature/update-ci'
        run: |
          echo ${{ github.ref }}
          git checkout main
          git pull origin main
          git merge origin/feature/update-ci --no-edit
          #git push origin main_test
