name: PR Test and Label Workflow

on:
  pull_request:
    types: [labeled, unlabeled]

permissions:
  issues: write  # Ensure write access to issues (needed to add/remove labels)

jobs:
  test:
    runs-on: self-hosted

    steps:
      # Step 1: Check if the label triggering the tests is added
      - name: Check if 'run-tests' label is added
        if: ${{ github.event.label.name == 'bug' }}
        run: |
          echo "Label 'bug' added. Proceeding with tests."

      # Step 2: Run tests
      - name: Run tests
        run: |
          # Replace this with your test script or commands
          pwd
      
      # Step 3: Check if tests passed
      - name: Check if tests passed
        if: ${{ success() }}
        run: |
          echo "Tests passed."

      # Step 4: Remove 'run-tests' label and add 'passed' label
      - name: Remove 'bug' label and add 'pass_CEFI_MOM6_RT_container' label
        if: ${{ success() }}
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"labels":["pass_CEFI_MOM6_RT_container"]}' \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels"

      # Step 5: If tests failed, do not add 'passed' label, but remove the 'run-tests' label
      - name: Remove 'bug' label on failure
        if: ${{ failure() }}
        run: |
          curl -X DELETE \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels/bug"
