name: Deploy Artifact

on:
  push:
    branches: [deploy]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      # Pull a container with Apptainer pre-installed
      - name: Convert Singularity to Docker using Apptainer container
        run: |   
          ls -l -h 
          pwd
